// ============================================================
// WLOG — Public API
// ============================================================

// Types
export type {
  Bit, Slot60, ChunkCoord, Base, Orientation,
  Mode4, Line7, Point3, Tile16, B8,
  Expr, Value, Opcode, LOG, Program,
  Marker, Clock, ConfigSeed, Header, WLOG,
  Config, Runtime, Event,
} from "./core/types.js";

export {
  O, I, slot, b8, ZERO_B8,
  EXOR, EAND, EOR, ENOT, ENOR, ENAND, EMONAD, EFUNCTOR,
  ETile, EMode, ESlot, EBits,
  VBit, VTile, VMode, VSlot, VBits,
  Sync, Wait, RotateL, RotateR, Join, Split,
  Emit, Hash, Map, Load, SetMode, SetLine, SetPoint,
  Done, Step, log_,
} from "./core/types.js";

// Bit helpers
export {
  bitNot, bitAnd, bitOr, bitXor,
  bitsNot, bitsAnd, bitsOr, bitsXor,
  rotL8, rotR8,
  b8ToUint8, uint8ToB8, b8ToString,
} from "./core/bits.js";

// Evaluator
export { evalExpr, runOpcode } from "./core/eval.js";

// Runtime
export { seedConfig, stepRuntime, runAll, runLazy, initRuntime } from "./core/runtime.js";

// DOM renderer (browser-only)
export type { Grid } from "./ui/dom.js";
export { buildGrid, applyEventToDOM, WLOG_CSS } from "./ui/dom.js";

// Infinite canvas
export type { PeerMessage, SerializedLOG, ChunkStore } from "./core/canvas.js";
export {
  pixelToAddress, addressToPixel,
  serializeLOG, deserializeLOG, makePeerMessage,
  tickLamport,
  programAppend, programFromLogs, programToLogs,
  emptyChunkStore, getChunk, putChunk, applyPeerMessage,
} from "./core/canvas.js";

// Scene model and rendering
export type { Scene, SceneCell, SceneFrame } from "./core/scene.js";
export { emptyScene, reduceEvent } from "./core/scene.js";

export { slotToGridXY, gridXYToSlot } from "./core/layout.js";

export { renderSceneSvg } from "./projection/render-svg.js";
export { renderSceneCanvas } from "./projection/render-canvas.js";

export { stepEngine, runEngine, initSceneEngine } from "./core/engine.js";

// Polyform core
export type {
  PolyCellKind,
  PolyCell,
  Polyform,
  PolyTransform,
  PolyReplayEntry,
  PolyReplayLog,
  PolyWitness,
  PolyBounds,
  PolyBitboard64,
} from "./polyform/polyform.js";
export {
  polyCell,
  polyCellKey,
  emptyPolyform,
  polyformFromCells,
  polyformArea,
  polyformBounds,
  polyformWitness,
  applyPolyTransform,
  replayPolyTransforms,
  polyformToBitboard64,
  isPolyformConnected,
} from "./polyform/polyform.js";

// WOLOG language
export type {
  WOLOGContinuationTag,
  WOLOGDecoratorTiming,
  WOLOGSurfaceOpTag,
  WOLOGScalar,
  WOLOGTaggedValue,
  WOLOGRecordValue,
  WOLOGListValue,
  WOLOGValue,
  WOLOGContinuation,
  WOLOGThunk,
  WOLOGEffect,
  WOLOGSeedForm,
  WOLOGJoinForm,
  WOLOGSplitForm,
  WOLOGMoveForm,
  WOLOGRotateForm,
  WOLOGFlipForm,
  WOLOGMatchForm,
  WOLOGTraceForm,
  WOLOGStepForm,
  WOLOGSyncForm,
  WOLOGHaltForm,
  WOLOGSurfaceForm,
  PolyformDecorator,
  PolyformProgram,
  WOLOGSeedCoreOp,
  WOLOGTransformCoreOp,
  WOLOGMatchCoreOp,
  WOLOGCallCoreOp,
  WOLOGBranchCoreOp,
  WOLOGContCoreOp,
  WOLOGCoreOp,
  WOLOGCoreProgram,
  WOLOGReplayEntry,
} from "./polyform/language.js";
export {
  WOLOG_REQUIRED_CONTINUATIONS,
  WOLOG_RESERVED_CONTINUATIONS,
  WOLOG_DECORATOR_TIMINGS,
  WOLOG_SURFACE_OPS,
  continuation,
  definePolyformProgram,
  decoratorTargets,
  requiredContinuations,
} from "./polyform/language.js";

// Aztec slide rule library
export type {
  BasisFamily,
  CodepointGroup,
  SampleKind,
  PolynomialDegree,
  PolynomialProperty,
  Instrument,
  PackedLayout,
  ProjectionKind,
  PackedCodepoint40Octets,
  PackedCodepoint40Groups5,
  PackedCodepoint40,
  SymbolicCodepoint,
  VirtualCodepoint,
  PolynomialClass,
  SquareCoords,
  TriangleCoords,
  HexCoords,
  CubeCoords,
  GenericCoords,
  BasisCoords,
  BasisCell,
  FunctionalTagPointer,
  SvgProjection,
  Scene25DProjection,
  Volume3DProjection,
  Projection,
  SmithChartInput,
  GenailleRodsInput,
  BinaryGuessInput,
  AztecCarrier,
  MaxiCodeCarrier,
  MaxiCodeMode,
  StructuredCarrierMessage,
  BeeTagCarrier,
  Code16KCarrier,
  Code16KMode,
  Code16KStartCodeSet,
  Code16KStartShift,
  Code16KConcatenationMeta,
  Code16KChecksumMeta,
  BeeTagCodebookMode,
  PolygonAcquisitionTarget,
  PolygonGridSpec,
  PolygonClockRecoveryModel,
  PolygonalCarrier,
  Carrier,
  CarrierEnvelope,
  CarrierReconcileResult,
  PolygonCell,
} from "./carriers/aztec-slide-rule.js";
export {
  BASIS_FAMILIES,
  CODEPOINT_GROUPS,
  SAMPLE_KINDS,
  POLYNOMIAL_DEGREES,
  POLYNOMIAL_PROPERTIES,
  INSTRUMENTS,
  CODEPOINT_FLAGS,
  normalizeSymbolicCodepoint,
  packedCodepoint40FromOctets,
  packedCodepoint40FromGroups5,
  virtualCodepointFromSymbolic,
  virtualCodepointFromPacked40,
  virtualCodepointRoundtrip,
  classifyPolynomialClass,
  basisCell,
  basisNeighbors,
  mapTagPointer,
  buildSvgProjection,
  buildScene25DProjection,
  buildVolume3DProjection,
  buildSmithChartSvg,
  buildGenailleRodsSvg,
  buildBinaryGuessSurfaceSvg,
  projectToAztecCarrier,
  projectToMaxiCodeCarrier,
  projectToBeeTagCarrier,
  projectToCode16KCarrier,
  beeTagFromIdentity15,
  beeTagIsOrientationValid,
  enumerateBeeTagOrientationValidIdentities,
  enumerateBeeTagMasterIdentities,
  enumerateBeeTagAuthoritativeMasterIdentities,
  getBeeTagCodebookStrategy,
  setBeeTagCodebookStrategy,
  CODE16K_MODES,
  normalizeCode16KPayload,
  computeCode16KChecksums,
  validateCode16KChecksums,
  validateCode16KCarrierStructure,
  projectToPolygonalCarrier,
  projectBarcodeTrinity,
  projectCarrierQuartet,
  projectCarrierSuite,
  buildCarrierEnvelope,
  canonicalPolyformHashFromCodepoint,
  reconcileCarrierEnvelopesWithCanonical,
  reconcileCarrierEnvelopes,
  reconcileCarrierEnvelopesAgainstCanonical,
  reconcileCarriers,
  reconcileCarriersAgainstCanonical,
  renderWorkedExample,
  MAXICODE_MODES,
} from "./carriers/aztec-slide-rule.js";

// Binary / Aztec embedding layer
export type {
  AztecInstruction,
  AztecTraceEntry,
  AztecReplayResult,
} from "./core/binary.js";
export {
  BitView,
  DataStream,
  AZTEC_VERSION,
  AztecOpcode,
  mask64,
  rotl64,
  rotr64,
  flip64,
  shl64,
  shr64,
  xor64,
  encodeAztecInstruction,
  decodeAztecInstruction,
  assembleAztecProgram,
  appendVersion,
  runAztecProgram,
  bytesToHex,
  hexToBytes,
  xorBytes,
  xorEncryptHex,
  xorDecryptHex,
  openAztecEmbedding,
  closeAztecEmbedding,
  formatMask64,
  formatTraceLog,
  aztecOpcodeName,
  AZTEC_EMBEDDING_SHACL_TURTLE,
  AZTEC_TRACE_SHACL_TURTLE,
} from "./core/binary.js";

// Semantic web / BCP 47 integration
export type {
  Bcp47TagParts,
  WellFormedLanguageTag,
  NormalizedLanguageTag,
  BasicLanguageRange,
  LanguageTagContract,
  LanguageLiteral,
  TurtleTriple,
  SemanticAztecResource,
  CarrierResource,
} from "./semantic/semantic-web.js";
export {
  isWellFormedLanguageTag,
  asWellFormedLanguageTag,
  parseLanguageTag,
  normalizeLanguageTagCase,
  normalizeLanguageTag,
  asBasicLanguageRange,
  parseLanguageTagContract,
  sameLanguageTag,
  basicFilterLanguageTags,
  lookupLanguageTag,
  languageLiteral,
  turtleLanguageLiteral,
  turtleNamedNode,
  turtleLiteral,
  serializeTurtle,
  semanticAztecTriples,
  serializeSemanticAztecResource,
  codepointTriples,
  aztecCarrierTriples,
  maxiCodeCarrierTriples,
  beeTagCarrierTriples,
  code16kCarrierTriples,
  carrierTriples,
  serializeCarrier,
  BCP47_LANGTAG_SHACL_TURTLE,
  CARRIER_SHACL_TURTLE,
  CODE16K_CARRIER_SHACL_TURTLE,
  SEMANTIC_WEB_SHACL_TURTLE,
} from "./semantic/semantic-web.js";

// SPARQL query builder
export type {
  SparqlVariable,
  SparqlFilter,
  SparqlOrderBy,
  SparqlSelectQuery,
  SparqlTriplePattern,
  SparqlConstructQuery,
  SparqlQuery,
} from "./semantic/sparql.js";
export {
  WOLOG_SPARQL_PREFIXES,
  spqVar,
  triple,
  filter,
  select,
  construct,
  toSparqlString,
  uri,
  literal,
  langLiteral,
  orderAsc,
  orderDesc,
  CARRIER_QUERIES,
  POLYFORM_QUERIES,
  VIRTUAL_CODEPOINT_QUERIES,
  queryAllCarriers,
  queryCarriersByFamily,
  queryCarriersByRole,
  queryAztecCarriers,
  queryMaxiCodeCarriers,
  queryBeeTagCarriers,
  queryCode16KCarriers,
  queryCarrierCounts,
  queryPolyformsByFamily,
  queryReplays,
  queryCodepointsByFamily,
  queryCodepointByAlias,
} from "./semantic/sparql.js";

// OWL Ontology (class hierarchy and properties)
export type { WOLOGClass, WOLOGObjectProperty, WOLOGCarrierRole } from "./semantic/ontology.js";
export {
  WOLOG_ONTOLOGY_PREFIXES,
  WOLOG_ONTOLOGY_TURTLE,
  CARRIER_ONTOLOGY_TURTLE,
  WOLOG_CLASS_HIERARCHY,
  WOLOG_CARRIER_ROLES,
} from "./semantic/ontology.js";

// RDF Resources (real-world entities identified by URIs)
export type {
  ResourceKind,
  ResourceMetadata,
  ResourceIdentity,
  PhysicalObjectResource,
  DigitalArtifactResource,
  SceneResource,
  TransformEventResource,
  WitnessReceiptResource,
  SceneProjectionResource,
  WOLOGResource,
  GeoLocation,
  SceneBounds,
} from "./semantic/resources.js";
export {
  WOLOG_RESOURCE_PREFIXES,
  RESOURCE_NAMESPACES,
  generateResourceUri,
  generateCarrierUri,
  createPhysicalObject,
  createDigitalArtifact,
  createScene,
  createTransformEvent,
  createWitnessReceipt,
  createSceneProjection,
  resourceTriples,
  serializeResource,
  serializeResources,
  getResourceSummary,
  RESOURCE_QUERIES,
} from "./semantic/resources.js";

// SKOS Knowledge Organization
export type {
  UnicodeAddress,
  ConceptMetadata,
  ConceptSchemeMetadata,
  SkosConcept,
  SkosConceptScheme,
  SkosCollection,
  SkosResource,
  DuodecimalDigit,
} from "./semantic/skos.js";
export {
  SKOS_PREFIXES,
  SKOS_NAMESPACES,
  DUODECIMAL_DIGITS,
  DUODECIMAL_NAMES,
  unicodeToDuodecimal,
  duodecimalToUnicode,
  generateUnicodeAddress,
  getUnicodeBlock,
  generateConceptUri,
  conceptTriples,
  conceptSchemeTriples,
  collectionTriples,
  skosTriples,
  serializeSkosResource,
  WOLOG_BASIS_FAMILY_SCHEME,
  WOLOG_CARRIER_ROLE_SCHEME,
  WOLOG_INSTRUMENT_SCHEME,
  WOLOG_BASIS_FAMILY_CONCEPTS,
  WOLOG_CARRIER_ROLE_CONCEPTS,
  WOLOG_INSTRUMENT_CONCEPTS,
  DUODECIMAL_CLASSIFICATION_SCHEME,
  DUODECIMAL_DIGIT_CONCEPTS,
  createBasisFamilyScheme,
  createCarrierRoleScheme,
  createInstrumentScheme,
  createDuodecimalScheme,
  SKOS_QUERIES,
  notationToUnicodeAddress,
  unicodeAddressToNotation,
} from "./semantic/skos.js";

// Frame types (WLOG = river, frames = photographs)
export type {
  WorldScene, ChunkScene, FrameSpec, FrameSnapshot,
  BoundedScene, CellSnapshot, Bounds,
  RenderSource, FrameStatus, FrameDiff,
} from "./core/frame.js";

export type { ChunkKey } from "./core/frame.js";
export {
  chunkKey as chunkKey,
  parseChunkKey,
  emptyBounds,
  expandBounds,
  boundsArea,
} from "./core/frame.js";

// World builder (builds WorldScene from WLOG, captures frames)
export {
  buildWorldScene,
  captureFrame,
  getFrameStatus,
  refreshFrame,
  diffFrames,
} from "./core/world-builder.js";

// Viewport (zoom, pan, focus)
export type { ViewportState, UIMode } from "./core/viewport.js";
export { Viewport } from "./core/viewport.js";

// Composer (data-attribute overlay layer)
export type {
  ComposerState,
  ComposerIntent,
  AttrPatch,
  CellOverlay,
  ComposerMode,
} from "./ui/composer.js";
export {
  emptyComposerState,
  toggleSelection,
  clearSelection,
  applyPatchToSelection,
  setComposerMode,
  eyedropperAttrs,
  clearOverlay,
  projectCellAttrs,
  cellKey,
  parseCellKey,
  deriveCellAttrs,
  isSelected,
  isHovered,
  getSelectedCount,
} from "./ui/composer.js";

// RIF Rule Layer
export type {
  RIFDialect,
  RIFCondition,
  RIFAtomic,
  RIFExternal,
  RIFTerm,
  RIFSlot,
  RIFFrame,
  RIFLiteral,
  RIFRule,
  RIFDocument,
  RIFImport,
  RIFPrefix,
  PolyformRule,
  ConstrainedHornClause,
  AztecConstraint,
  HornAtom,
  HornTerm,
  HornClauseRule,
} from "./semantic/rif.js";
export {
  RIF_PREFIXES,
  rifTerm,
  rifAtomic,
  rifAnd,
  rifOr,
  rifExternal,
  rifFrame,
  rifSlot,
  rifImplies,
  rifFact,
  rifQuery,
  rifRuleToString,
  rifDocumentToString,
  POLYFORM_INFERENCE_RULES,
  rifRulesToTurtle,
  hornVar,
  hornConst,
  hornBeeTag,
  hornMaxiCode,
  hornAtom,
  chc,
  chcRule,
  chcToString,
  chcRuleToString,
  chcToTurtle,
  aztecConstraint,
  BARCODE_QUARTET_CHC_RULES,
  BARCODE_TRINITY_CHC_RULES,
  POLYFORM_CHC_RULES,
} from "./semantic/rif.js";

// Quartet reconciliation proof demo
export type {
  QuartetCarrierReceiptRow,
  QuartetScenarioReceipt,
  QuartetDeterminismReceipt,
  QuartetReconciliationProofReceipt,
  QuartetReconciliationProofArtifact,
} from "./carriers/quartet-reconciliation-demo.js";
export {
  buildQuartetReconciliationProofDemo,
} from "./carriers/quartet-reconciliation-demo.js";

// Logic and Proof Layer
export type {
  LogicalOperator,
  Literal,
  AtomicFormula,
  CompoundFormula,
  Formula,
  Rule,
  ProofStep,
  Proof,
  InferenceResult,
  PolyformBinding,
  Constraint,
  Query,
} from "./semantic/logic.js";
export {
  LOGIC_PREFIXES,
  uri as logicUri,
  literal as logicLiteral,
  variable,
  atomic,
  and,
  or,
  not,
  implies,
  rule,
  formatFormula,
  formulaToTriples,
  matchAtomic,
  evaluateFormula,
  applyRule,
  prove,
  polyformQuery,
  carrierQuery,
  conceptQuery,
  formatQuery,
  queryToTriples,
  POLYFORM_LOGIC_RULES,
  SEMANTIC_INFERENCE_RULES,
  deriveProperties,
  verifyProof,
} from "./semantic/logic.js";

// Polynomial Truth Table (Boolean functions ↔ polyform basis)
export type {
  BooleanFunctionName,
  BooleanValue,
  TruthTableRow,
  PolyformSignature,
  TermOrdering,
  GroupingType,
  SequencingType,
  ClosureType,
  PolynomialCoefficient,
  PolynomialContinuation,
  TruthTableCell,
  PolyformAsTruthTable,
  PolyformBasisName,
} from "./polyform/polynomial-truth-table.js";
export {
  BOOLEAN_FUNCTION_NAMES,
  TRUTH_TABLES,
  evaluateBooleanFunction,
  truthTableToBits,
  bitsToHex,
  encodePolyformSignature,
  decodePolyformSignature,
  polyformSignatureToMaxiCodeID,
  maxiCodeIDToPolyformSignature,
  createPolyformFromTruthTable,
  polyformToTruthTableBits,
  polyformToAztecWitness,
  polyformToBEEtagPackets,
  polynomialContinuation,
  evaluatePolynomial,
  CLOSURE_FUNCTION,
  applyClosure,
  POLYFORM_BASIS_NAMES,
  basisNameToFunction,
  polyformToHornTerm,
  TRUTH_TABLE_TO_POLYFORM,
} from "./polyform/polynomial-truth-table.js";

// Omicron Optical-Rewriting Machine
export type {
  Tick,
  Bit5,
  Bit40,
  InversionMode,
  LinkType,
  AztecCore,
  MaxiTile,
  BEEtagFunction,
  OmMachine,
  MaxiScene,
  Frame,
  HexDirection,
  PolyformBasisType,
  BitMetaCircular,
  RewriteRule,
} from "./core/omicron-machine.js";
export {
  MASTER_PERIOD,
  SYNC_INTERVAL,
  SYNC_POINTS,
  FANO_POINTS,
  BEE_TAG_BITS,
  AZTEC_CORE_BITS,
  MAXICODE_DIRECTIONS,
  createAztecCore,
  rotateAztecCore,
  aztecToFanoPoints,
  createMaxiTile,
  createMaxiScene,
  toggleMaxiLinks,
  retileScene,
  createBEEtagFunction,
  evaluateBEEtag,
  centralInversion,
  isSyncPoint,
  getSyncPointIndex,
  isFanoPoint,
  getFanoPhase,
  createOmMachine,
  tickMachine,
  transition,
  projectMachine,
  projectToString,
  kinematicCycle,
  runKinematicCycle,
  machineToHornTerms,
  createCHCRule,
  createBitMetaCircular,
  interpretBitMetaCircular,
  fixedPointBitMetaCircular,
  aztecRewrite,
  maxiRewrite,
  beeRewrite,
  compositeRewrite,
  OOM_PREFIXES,
  machineToTurtle,
  OOM_SHACL_TURTLE,
  twoOfFiveEncode,
  twoOfFiveDecode,
} from "./core/omicron-machine.js";

// Canonical Control Plane
export type {
  Lane,
  ContextType,
  NumSys,
  ExtensionDepth,
  ControlWord,
  ControlWordWithContext,
  ControlContext,
  ParsedByte,
  ParseState,
  ControlPlaneConfig,
  SerializedControlWord,
  ControlAddress,
  ChannelName,
  NumSysName,
} from "./core/control-plane.js";
export {
  CONTROL_MARKER,
  FLAG_BIT,
  DATA_MASK,
  CONTROL_MASK,
  CHANNELS,
  CHANNEL_NAMES,
  NUMERICAL_SYSTEMS,
  NUMSYS_NAMES,
  LANES_PER_CHANNEL,
  CONTEXTS_PER_LANE,
  TOTAL_CONTROL_ADDRESSES,
  CONTROL_WORD_SIZE,
  EXTENSION_DEPTH_MAX,
  getFlagBit,
  isControlByte,
  isDataByte,
  isCobsDelimiter,
  makeControlByte,
  makeDataByte,
  parseChannel,
  isChannelByte,
  parseControlWord,
  parseControlSequence,
  computeControlAddress,
  decodeControlAddress,
  getContextTypeName,
  getContextTypeDescription,
  parseContextByte,
  getNumSysName,
  parseNumSys,
  isExtensionSystem,
  isReservedSystem,
  encodeNumSys,
  createExtensionDepth,
  incrementExtensionDepth,
  getMaxExtensionDepth,
  isExtensionDepthExceeded,
  enumerateExtensionSystems,
  createParseState,
  parseByte,
  parseStream,
  serializeControlWord,
  serializeControlContext,
  encodeCobsWithControlPlane,
  generateControlMatrix,
  getChannelName,
  DEFAULT_CONTROL_PLANE_CONFIG,
  STRICT_CONTROL_PLANE_CONFIG,
  LENIENT_CONTROL_PLANE_CONFIG,
  formatControlWord,
  formatControlAddress,
  formatNumSys,
  isValidControlSequence,
  CONTROL_PLANE_PREFIXES,
  controlWordToTurtle,
  controlMatrixToTurtle,
} from "./core/control-plane.js";
